### ISSUE TITLE
Example command lines for gnuplot would be nice

### ISSUE THREAD

**Issue by jstuyts** [scaidermern/audria#3]
Can the command lines for gnuplot used to generate the graphs be added to the documentation? This will save a lot of time for people unfamiliar with gnuplot.

**Comment by jstuyts** [comment]
Sorry, I searched for `gnuplot` instead of `plot`. I found the command lines now.

**Comment by scaidermern** [comment]
Great :) Maybe I can improve the documentation regarding gnuplot a little.
